config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users,only:[:edit,:update]
  resources :rooms,only:[:new, :create, :destroy] do
    resources :messages,only:[:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user        #この記述でuserを定義することでuserメソッド(.user)が使えるようになっている
  belongs_to :room        #この記述でroomを定義することでroomメソッド(.room)が使えるようになっている
  has_one_attached :image #この記述でimageを定義することでimageメソッド(.image)が使えるようになっている
  has_one_attached :file  #この記述でfileを定義することでfileメソッド(.file)が使えるようになっている

  validates :content, presence: true, length: {maximum: 140}, unless: :was_attached? 

  def was_attached?
    self.image.attached? || self.file.attached?   
  end
end

#7行目…unlessオプションにメソッド名を指定： 「メソッドの返り値がfalseならばバリデーションによる検証を行う」という意味
#7行目あと、 validates に if や unless で条件を付ける時は末尾に付けた方が分かりやすいです。
#「このバリデーションを条件の時に行う（行わない）」という意味なので上記のように末尾に付けた方が読みやすいです。

#attached?メソッド  レコードにファイルが添付されているかどうかで、trueかfalseを返すメソッド。 
#attached = 添付 

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  validates :name, presence: true

  has_many :room_users
  has_many :rooms,through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters,if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
    @message = Message.new
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      helpers = Rails.application.routes.url_helpers
      ActionCable.server.broadcast "message_channel", content: {
        id: @message.id,
        content: @message.content,
        user_name: @message.user.name,
        created_at: I18n.l(@message.created_at),
        image: @message.image.attached? ? helpers.rails_representation_url(@message.image.variant(resize: '500x500'), only_path: true) : nil,
        file: @message.file.attached? ? helpers.rails_blob_path(@message.file, only_path: true) : nil, 
      }
      # redirect_to room_messages_path(@room) ←chat-appの時の記述
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
    # 成功時の表示処理
    rescue => e
    logger.error(e)
    logger.error(e.record.errors.full_messages)
    # エラー時の表示処理
  end

  private

  def message_params
    params.require(:message).permit(:content, :image, :file).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room=Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name,user_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRogear</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
    <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%=link_to "チャットルーム削除",room_path(@room),method: :delete%>
    </div>
  </div>
</div>

<div class="messages" id="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%=form_with model: [@room, @message], class: "form" do |f|%>
  <div class="form-input"> 
    <%=f.text_field :content, class: "form-message", id: 'message_text', placeholder: "メッセージ入力" %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%=f.file_field :image, class: "hidden", id: 'message_image'%>
    </label>
    <label class="form-image">
      <span class="image-file">ファイル</span>
      <%=f.file_field :file, class: "hidden", id: 'message_file'%>
    </label>
    <%=f.submit "送信", class: "form-submit"%>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%=message.user.name%>
    </div>

    <div class="message-date">
      <%=l message.created_at%>
    </div>
  </div>

  <div class="lower-message">
    <div class="message-content">
      <%=message.content%>
    </div>
    <%=image_tag message.image.variant(resize:'500x500'), class: "message-image" if message.image.attached?%>
    <%=link_to "添付ファイル", url_for(message.file), class: "message-file" if message.file.attached?%>
  </div>
</div>



<%# このファイルは実際に送信するメッセージのファイル %>
<%# 4行目がユーザーネーム、8行目が日付、14がメッセージ、16行目が画像、17行目がその他ファイル %>
<%#16行目 variantメソッド…ファイルの表示サイズを指定できる。Active Storageを導入している場合に使用可能なメソッド。指定された横幅と高さを超えるサイズにはならない。 %>
<%# 17行目 候補 url_for(message.file) %>

app/views/messages/_side_bar.html.erb
<div class="side-bar">
  <div class="side-header">
    <div class="header-name">
      <%= link_to current_user.name,edit_user_path(current_user)%>
    </div>
    <div class="create-room">
      <%=link_to "グループ作成",new_room_path%>
    </div>
  </div>

  <div class="rooms">
    <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
      <%=link_to room.name,room_messages_path(room)%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar"%>
  </div>
  <div class="chat">
    <%= render "main_chat"%>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%=render "messages/side_bar"%>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      <select name="room[user_ids][]">
        <option value="">ユーザーを選んで下さい</option>
        <% User.where.not(id: current_user.id).each do |user|%>
          <option value=<%= user.id %>><%= user.name %></option>
        <% end %>
      </select>
      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>